<a href="https://colab.research.google.com/github/MingzheHu-Duke/RL_Landmark_Tracking/blob/mh%2Fimage_processing/MaxPadding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Motivation
The input size of the images (enviroment) *2D* may be different. We want to reform them to the same size, but also keep the same spatial resolution. Simply resize the images will change the aspect ratio and also change the spatial resolution. So padding the images to the same size before resizing would make more sense.

In [29]:
import numpy as np

def pad_max(images, ratio=None, value=0, tie_break=np.floor):
  """
  Pad the given sequence of image arrays to the shape that fit the biggest array
  ratio:
  """
  shapes = np.array([x.shape for x in images])
  if ratio is not None:
    ratio = np.zeros_like(shapes) + ratio
  else:
    ratio = np.ones_like(shapes) - 1
  # Maximum size along the first axis
  max_size = shapes.max(axis=0, keepdims=True)
  # See how many pixels we need to pad
  margin = max_size - shapes
  # How many pixesl
  pad_before = tie_break(margin * ratio.astype(float)).astype(int)
  pad_after = margin - pad_before
  # Stack the pad_before and pad_after
  pad = np.stack([pad_before, pad_after], axis=2)
  return [np.pad(x, w, mode="constant", constant_values=value) for x, w in zip(images, pad)]

In [37]:
# See if ou method does work
test = [np.ones(shape=(i, 10 - i, 3)) for i in range(1, 10)]
result = pad_max(test, ratio=1, value=255)

print([x.shape for x in result])
for i in range(9):
  print(f"Padded Image{i}")
  print(result[i][:, :, 0])
  print("\n")

[(9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3), (9, 9, 3)]
Padded Image0
[[255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]]


Padded Image1
[[255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255.   1.   1.   1.   1.   1.   1.   1.   1.]
 [255.   1.   1.   1.   1.   1.   1.   1.   1.]]


Pa